In [27]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import cv2

device="cuda" if torch.cuda.is_available()  else "cpu"

In [28]:
#Scalar
scalar=torch.tensor(8)
scalar

tensor(8)

In [29]:
scalar.ndim

0

In [30]:
#Get The data from the scalar

scalar.item()

8

In [31]:
#Creating Vectors

vector1=torch.tensor([1,2])
print(vector1)
print(vector1.shape)

#From Numpy array
arr=np.array([1,2])
npVector=torch.tensor(arr) # npVector=torch.from_numpy(arr)
npVector

tensor([1, 2])
torch.Size([2])


tensor([1, 2], dtype=torch.int32)

In [32]:
#Matrices
matrix=torch.tensor([[1,2],[2,3],[3,4]])
print(matrix)
print(matrix.ndim)

#Matrices from numpy array
arr1=np.array([[1,2],[2,3],[3,4]])
matrixNp=torch.tensor(arr1)
print(matrixNp)
print(matrixNp.shape)
print(matrixNp[0][0].item())# The indexing will always result in a tensor, hence we call item()

tensor([[1, 2],
        [2, 3],
        [3, 4]])
2
tensor([[1, 2],
        [2, 3],
        [3, 4]], dtype=torch.int32)
torch.Size([3, 2])
1


In [33]:
#Creating Tensors (Matrices With More than 3 dimensions

tensor1=torch.tensor([[[1,2,3],[3,4,5]],[[2,3,5],[1,1,1]]])
print(tensor1)
print(tensor1.ndim)

tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[2, 3, 5],
         [1, 1, 1]]])
3


In [34]:
#Just lil experiments -_-
tensor2=torch.tensor([[[1,2],
          [3,3.1]]])
print(tensor2)

tensor([[[1.0000, 2.0000],
         [3.0000, 3.1000]]])


In [35]:
#Accessing Members of a tensor
print(tensor1[0][0][0].item())
print(tensor1[0][0])


1
tensor([1, 2, 3])


In [36]:
#Creating Random Tensors 
randTensor=torch.rand(2,2,2)

#Applying a Transformation to the tensor
randTensor=randTensor*200
print(randTensor)

#StandardScaling the tensor
randTensor=(randTensor-torch.mean(randTensor))/torch.std(randTensor)
print(randTensor)

#Sum, min and max
print(f"The sum of elements is {torch.sum(randTensor)}")
print(f"The maxm of elements is {torch.max(randTensor)}")
print(f"The minm of elements is {torch.min(randTensor)}")





tensor([[[ 26.6372, 186.9196],
         [118.7159, 173.8809]],

        [[113.5431, 148.2188],
         [ 85.8809, 177.0886]]])
tensor([[[-1.8783,  1.0668],
         [-0.1864,  0.8272]],

        [[-0.2815,  0.3557],
         [-0.7897,  0.8862]]])
The sum of elements is -8.940696716308594e-07
The maxm of elements is 1.0668165683746338
The minm of elements is -1.8783252239227295


In [37]:
#Creating tensors similar to images

image_1=torch.rand(size=(224,224,3))
image_1


tensor([[[0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969],
         [0.8317, 0.1053, 0.2695],
         ...,
         [0.8537, 0.5697, 0.2088],
         [0.6539, 0.3397, 0.9565],
         [0.0660, 0.3421, 0.0172]],

        [[0.3031, 0.6576, 0.9813],
         [0.5840, 0.9902, 0.5978],
         [0.7888, 0.9008, 0.9180],
         ...,
         [0.6820, 0.5322, 0.8510],
         [0.4556, 0.1844, 0.8533],
         [0.5698, 0.3568, 0.1704]],

        [[0.6172, 0.0231, 0.6317],
         [0.7472, 0.0614, 0.1727],
         [0.1405, 0.9203, 0.9251],
         ...,
         [0.6792, 0.4989, 0.0933],
         [0.3064, 0.6272, 0.5955],
         [0.8636, 0.8345, 0.2273]],

        ...,

        [[0.8819, 0.3599, 0.1989],
         [0.5711, 0.5387, 0.1378],
         [0.9763, 0.5521, 0.6004],
         ...,
         [0.7943, 0.1790, 0.9954],
         [0.6617, 0.9871, 0.5877],
         [0.7375, 0.1551, 0.7881]],

        [[0.3759, 0.7442, 0.8621],
         [0.7548, 0.6381, 0.0106],
         [0.

In [38]:
#Creating Tensors  With Zeros Or Ones
zeros=torch.zeros(size=(2,3,3),dtype=torch.int32)
ones=torch.ones(size=(2,3,3),dtype=torch.int32)
ones,zeros

(tensor([[[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]],
 
         [[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]]], dtype=torch.int32),
 tensor([[[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],
 
         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]], dtype=torch.int32))

In [39]:
#Do Some Cool Matrix Multiplication Stuff
print(zeros@ones)



tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=torch.int32)


In [40]:
#Create a range  of values inside  a tensor
ranges=torch.arange(20,1,-1)
ranges

tensor([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
         2])

In [41]:
#Creating a tensor alike another tensor

newTensor=torch.ones_like(ranges)
newTensor

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h1><b>Tensor DataTypes</b></h1>

In [55]:
#normal float32 
float32=torch.tensor([[1,2.0,3]],dtype=torch.float32 #
                     ,device="cpu",#use cpu or gpu
                     requires_grad=False)
print(float32)

#Other Data Types : float32, int8,int32,int64,int16,complex32,complex64 etc etc


#We can also create numpy array from tensors
np=float32.numpy() #Remember that the tensor has to be a cpu tensor as numpy has no support for gpu
np

tensor([[1., 2., 3.]])


array([[1., 2., 3.]], dtype=float32)

<h1><b>Getting Information/Attributes from a tensor</b></h1>

In [43]:
print(float32.shape)
print(float32.device)
print(float32.dtype)

torch.Size([1, 3])
cuda:0
torch.float32


<h1><b>Manipulating Tensors</h1>
<h3>Addition
Subtraction
Element Wise Multiplication
Division
Matrix Multiplication</b></h3>

In [44]:
#addition
print(float32+float32) #The Dimensions must match for addition and subtraction

#Element wise  multiplication
print(float32*float32)

#Matrix Multiplication
print(float32@float32.T)  #Shape Of Float32=(1,3) float32.T=(3,1)

tensor([[2., 4., 6.]], device='cuda:0')
tensor([[1., 4., 9.]], device='cuda:0')
tensor([[14.]], device='cuda:0')


In [45]:
#Min ,max , mean,argmin,argmax
#Cannot operate these on an int tensor
new_tensor=torch.tensor([[1,2,3],[3,4,5]],dtype=torch.int32)
new_tensor=new_tensor.type(torch.float32)
print(new_tensor.dtype)
print(torch.mean(new_tensor))
print(torch.argmin(new_tensor,axis=1)) #Returns The index of the minimum value
print(torch.argmax(new_tensor,axis=1)) #Returns The index of the minimum value

torch.float32
tensor(3.)
tensor([0, 0])
tensor([2, 2])


<h1><b>Reshaping , Viewing and Stacking Tensors</b></h1>

In [46]:
x=torch.arange(1.,31.)
x_re=x.reshape(2,15)  # just creates a new copy
print(x_re)

x_re=x.view(2,15)
x_re[:,1]=3 #Changing x_re changes x as both share  the same memory
x,x_re


x_stacked=torch.stack([x,x,x],dim=0) #Stacks 3 x's in a specified dimension
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15.],
        [16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28., 29.,
         30.]])


tensor([[ 1.,  3.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16.,  3., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
         29., 30.],
        [ 1.,  3.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16.,  3., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
         29., 30.],
        [ 1.,  3.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16.,  3., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
         29., 30.]])

In [47]:
#Squeezing, Unsqueezing and Permuting

#Squeeze - If any dimension is found to be '1' ,it removes the dimension and flattens the tensor
#-The returned tensor shares the storage with the input tensor, so changing the contents of one will change the contents of the other.

new=torch.rand(3,1)
print(new)
new=new.squeeze()
print(new)

#Unsqueeze - Adds 1 , dimension
new=new.unsqueeze(dim=0)
print(new)


#Permute - Returns a view of a tensor by swapping its dimensions
perm=torch.rand(3,5)
perm_permed=torch.permute(perm,(1,0))#Here (1,0) signifies that the 1th dimension is to be in the first place
print(perm_permed.shape)

perm2=torch.rand(3,4,5,6)
perm2_permed=torch.permute(perm2,(2,1,0,3))
perm2_permed.shape

tensor([[0.7786],
        [0.8016],
        [0.3649]])
tensor([0.7786, 0.8016, 0.3649])
tensor([[0.7786, 0.8016, 0.3649]])
torch.Size([5, 3])


torch.Size([5, 4, 3, 6])

<h1>Experimental section - Free to Ignore </h1>

In [48]:
new_ten=torch.rand(size=(3,4,5))
print(new_ten)

print(new_ten[1,2,3])

print(new_ten[:,2,3])

print(new_ten[1:,2,1:])

tensor([[[0.8325, 0.8324, 0.9382, 0.4561, 0.3427],
         [0.4075, 0.5637, 0.4735, 0.6656, 0.7461],
         [0.3946, 0.7927, 0.0130, 0.5498, 0.6315],
         [0.8832, 0.0827, 0.5123, 0.7747, 0.5146]],

        [[0.4381, 0.7884, 0.2626, 0.6280, 0.5841],
         [0.0609, 0.0901, 0.9290, 0.1491, 0.4579],
         [0.8595, 0.2389, 0.4285, 0.9068, 0.6739],
         [0.1857, 0.0013, 0.6637, 0.3250, 0.2551]],

        [[0.9134, 0.9205, 0.0640, 0.2996, 0.8763],
         [0.0851, 0.0685, 0.7487, 0.9526, 0.5312],
         [0.0555, 0.5351, 0.3162, 0.6036, 0.3111],
         [0.2959, 0.7271, 0.1596, 0.6651, 0.7346]]])
tensor(0.9068)
tensor([0.5498, 0.9068, 0.6036])
tensor([[0.2389, 0.4285, 0.9068, 0.6739],
        [0.5351, 0.3162, 0.6036, 0.3111]])


<h1>Reproducibility  Or Random Seed for  random values</h1>

In [49]:
torch.manual_seed(42)#This sets the seed to 45 , meaning the random numbers will be based off of this seed

t1=torch.rand(3,3)
torch.manual_seed(42)#Each seed works for one randomization

t2=torch.rand(3,3)
print(t1,t2)

print(t1==t2)#all the values are equal



tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]]) tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [51]:
t2=torch.tensor([[1,2],[2,3]],device="cpu") #create a tensor on a cpu
print(t2.device)

t2=t2.to(device)
print(t2.device)#Will convert the tensor to a gpu tensor if gpu is available


cpu
cuda:0


#Sadly This is going to be  the end of this notebook , hopefully we will continue in the next one